project_name: "om2vec-v2"
project_save_dir: "./experiment_logs" # Local directory for logs & checkpoints
training: true                      # true: train; false: test
accelerator: "gpu"                  # "gpu" or "cpu"
num_devices: 1                      # number of devices (GPUs)
dataloader: "prometheus"     # key matching a DataModule class in dataloaders/
checkpoint: ""                      # path to ckpt or empty
resume_training: false              # whether to resume if checkpoint provided
logger: "wandb"

data_options:
  train_data_files: ["/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/NuMu",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/EMinus",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/MuMinus",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/TauMinus",]
  valid_data_files: ["/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/NuMu",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/EMinus",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/MuMinus",
                     "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/felixyu/IceCube_MC_sensors/TauMinus"]
  train_data_file_ranges: [[0, 20], [0, 20], [0, 20], [0, 20]] # Ranges for each file in train_data_files
  valid_data_file_ranges: [[20, 24], [20, 24], [20, 24], [20, 24]] # Ranges for each file in valid_data_files
  shuffle_files: true   # If true, shuffles file order each epoch for training set
  max_seq_len: 512      # For padding/truncating photon sequences per sensor
  summary_stats_dim: 10 # Number of summary statistics

model_options:
  latent_dim_learned: 22
  transformer_d_model: 256
  transformer_nhead: 8
  transformer_num_encoder_layers: 6
  transformer_dim_feedforward: 1024
  transformer_activation: "gelu"
  transformer_norm_first: true
  transformer_dropout: 0.1
  zuko_nsf_hidden_features: 256
  zuko_nsf_num_flow_steps: 5
  zuko_nsf_num_bins: 8

training_options:
  batch_size: 512
  lr: 0.0001
  weight_decay: 0.01
  gradient_clip_val: 1.0
  beta_kl: 0.00001
  beta_kl_start: 0.
  beta_kl_warmup_epochs: 5
  epochs: 5
  save_epochs: 1                # Save checkpoint every N epochs
  save_top_k: 3                 # Save top K checkpoints based on monitor_metric
  monitor_metric: "val_loss"    # Metric to monitor for saving checkpoints
  monitor_mode: "min"           # "min" or "max" for monitor_metric
  num_workers: 4
  precision: "bf16-mixed"       # "bf16-mixed", "32-true", "16-mixed"
  test_precision: "bf16-mixed"  # Precision for test mode